const Menu = [
  {
    id: 1,
    image: "images/Breakfast/idli.jpg",
    name: "Idli",
    category: "Breakfast",
    price: 25,
    description:
      "Idli is a popular South Indian dish that is made from fermented rice and lentil batter. It is a steamed rice cake that is soft, fluffy, and often served with various accompaniments such as sambar (a lentil-based vegetable stew) and chutney.",
  },
  {
    id: 2,
    image: "images/Dinner/gujarati.jpg",
    name: "Gujarati Thali",
    category: "Dinner",
    price: 25,
    description: "It is a traditional meal from the western Indian state of Gujarat. It consists of a variety of vegetarian dishes served on a large plate or platter. Gujarati cuisine is known for its flavors, variety, and the balance of sweet, salty, and spicy tastes in its dishes.",
  },
  {
    id: 3,
    image: "images/Breakfast/maggi.jpg",
    name: "Maggi",
    category: "Breakfast",
    price: 25,
    description:
      "Maggi noodles are typically cooked by boiling them in water and then adding the included seasoning packet. They are known for their quick cooking time, making them a convenient meal or snack option. However, it's important to note that instant noodles, including Maggi noodles, are often considered a processed food and should be consumed in moderation as part of a balanced diet.",
  },
  {
    id: 4,
    image: "images/Breakfast/misal.jpg",
    name: "Misal Pav",
    category: "Breakfast",
    price: 25,
    description: "Misal pav is a popular Maharashtrian dish from India. It consists of a spicy curry made with sprouted moth beans (matki) or mixed legumes, topped with farsan (crispy savory snack), chopped onions, cilantro, and served with pav (soft bread rolls).",
  },
  {
    id: 5,
    image: "images/Lunch/aloo paratha.jpg",
    name: "Aloo Paratha",
    category: "Lunch",
    price: 25,
    description: "Aloo paratha is a popular Indian flatbread stuffed with a spiced mashed potato filling. It is a delicious and satisfying dish that is commonly enjoyed for breakfast or as a main course.",
  },
  {
    id: 6,
    image: "images/Breakfast/omelette.jpg",
    name: "Omelette",
    category: "Breakfast",
    price: 25,
    description: "An omelette is a classic dish made from beaten eggs cooked in a frying pan. It is a versatile dish that can be enjoyed for breakfast, brunch, or even as a light meal or snack.",
  },
  {
    id: 7,
    image: "images/Lunch/biryani.jpg",
    name: "Biryani",
    category: "Lunch",
    price: 25,
    description: "Biryani is a flavorful and aromatic rice dish that is popular in many parts of South Asia and the Middle East. It is made by cooking rice with meat, vegetables, or both, along with a blend of spices and herbs. Biryani is known for its rich flavors, fragrant spices, and the tender texture of the meat or vegetables.",
  },
  {
    id: 8,
    image: "images/Dinner/maharatra.jpg",
    name: "Mahrastrian Thali",
    category: "Lunch",
    price: 25,
    description: "A Maharashtrian thali is a traditional meal from the state of Maharashtra in western India. It typically consists of a variety of dishes that represent the diverse flavors and culinary traditions of the region. Maharashtrian cuisine is known for its bold and spicy flavors, as well as the use of locally available ingredients.",
  },
  {
    id: 9,
    image: "images/Lunch/chole bhature.jpg",
    name: "Chole Bhature",
    category: "Lunch",
    price: 25,
    description: "Chole bhature is a popular North Indian dish consisting of spicy chickpea curry (chole) served with deep-fried bread (bhature). It is a flavorful and satisfying combination that is often enjoyed as a main course or as a special treat.",
  },
  {
    id: 10,
    image: "images/Breakfast/pavbhaji.jpg",
    name: "Pav Bhaji",
    category: "Breakfast",
    price: 25,
    description: "Pav bhaji is a popular street food dish from Maharashtra, India. It consists of a spicy vegetable curry (bhaji) served with buttered and toasted pav (soft bread rolls). It is a flavorful and satisfying dish that is enjoyed as a snack or a light meal.",
  },
  {
    id: 11,
    image: "images/Lunch/chole kulcha.jpg",
    name: "Chole Kulcha",
    category: "Lunch",
    price: 25,
    description: "Chole kulcha is a popular North Indian dish that consists of spicy chickpea curry (chole) served with soft and fluffy kulchas. It is a flavorful and satisfying combination that is commonly enjoyed as a main course or street food.",
  },
  {
    id: 12,
    image: "images/Dinner/haryana.jpg",
    name: "Haryana thali",
    category: "Dinner",
    price: 25,
    description: "A Haryana thali refers to a traditional meal served in the state of Haryana, located in northern India. Haryana has a rich agricultural heritage, and its cuisine reflects the use of locally grown ingredients. A typical Haryana thali comprises a variety of dishes that showcase the flavors and culinary traditions of the region.",
  },
  {
    id: 13,
    image: "images/Lunch/dosa.jpg",
    name: "Dosa",
    category: "Lunch",
    price: 25,
    description: "Dosa is a popular South Indian dish that has gained widespread popularity across India and around the world. It is a fermented crepe or pancake made from a batter consisting of rice and black gram (urad dal). Dosa is typically thin, crispy on the outside, and soft on the inside. It is often served with various accompaniments and chutneys. ",
  },
  {
    id: 14,
    image: "images/Lunch/litichokha.jpg",
    name: "maggi",
    category: "Lunch",
    price: 25,
    description: "Litichokha is a traditional dish from the state of Bihar in India. It is a combination of two main components: litti and chokha.",
  },
  {
    id: 15,
    image: "images/Dinner/rajasthani.jpg",
    name: "Rajasthani Thali",
    category: "Dinner",
    price: 25,
    description: "A Rajasthani thali refers to a traditional meal served in Rajasthan, a state in northwestern India. It is a grand platter that offers a wide variety of dishes, providing a glimpse into the rich and vibrant culinary heritage of Rajasthan",
  },
  {
    id: 16,
    image: "images/Breakfast/sandwich.jpg",
    name: "Sandwich",
    category: "Breakfast",
    price: 25,
    description: "A sandwich is a food item that typically consists of one or more fillings placed between two slices of bread or a bread-like base. The fillings can vary widely and may include ingredients like meats, cheese, vegetables, spreads, condiments, and sauces.",
  },
  {
    id: 17,
    image: "images/Lunch/thalipitha.jpg",
    name: "Thalipeeth",
    category: "Lunch",
    price: 25,
    description: "Thalipeeth is a traditional and savory multigrain flatbread from the state of Maharashtra in Western India. It is made by combining different types of flours, spices, and herbs to create a flavorful and nutritious bread.",
  },
  {
    id: 18,
    image: "images/Dinner/southIndian.jpg",
    name: "South Indian Thali",
    category: "Dinner",
    price: 25,
    description: "A South Indian thali is a traditional meal from the southern region of India, known for its distinctive flavors and culinary traditions. It typically consists of a variety of vegetarian dishes served on a banana leaf or a large plate, showcasing the diverse and rich flavors of South Indian cuisine.",
  },
  {
    id: 19,
    image: "images/Breakfast/samosa.jpg",
    name: "Samosa",
    category: "Breakfast",
    price: 25,
    description: "Samosa is a popular savory snack or appetizer that originated in the Indian subcontinent. It is a deep-fried pastry filled with a spicy and flavorful mixture of potatoes, peas, and spices. Samosas are loved for their crispy exterior and delicious filling.",
  },
];

export default Menu;
